### ISSUE TITLE
[bug] "Error Invalid JSON format." is displayed. HiAnime parsing issue

### ISSUE THREAD

**Issue by jjtpjjj** [cranci1/Ryu#13] opened 2024-09-13 12:14 UTC
Steps to reproduce the issue:
① Open the "Ryu" app.
② Tap "Search".
③ Search for the title of the anime.
④ Play the anime you searched for.
⑤ Stop playback and return to Home etc. (An alternative method is to close the Ryu app itself.)
⑥ Play the anime you played in step ④ from Continue Watching on Home.
⑦ An error will be displayed.

Even if this error is displayed, you may be able to play the anime.
However, there are also cases where the anime cannot be played at all.

Even if this error is displayed, you may be able to play the anime.
However, there are also cases where the anime cannot be played at all.
![IMG_0949](https://github.com/user-attachments/assets/c9164ef0-3b08-463f-867a-8ab91aa20ed3)
![IMG_0948](https://github.com/user-attachments/assets/b4a9a098-a87d-4fd5-8dd8-3d588c8e8c62)

**Comment by cranci1** [comment] 2024-09-13 12:16
Yes i know, can you test the new testflight build that is out? (i've just pushed it, you may need to remove the item from the continue watching and then the issue is fixed if you are on the new build)

**Comment by jjtpjjj** [comment] 2024-09-13 12:19
Test fly build?

Does that mean an error occurs if I use the currently released ipa?

**Comment by cranci1** [comment] 2024-09-13 12:21
ohh if you are using the ipa you can try the latest one, the issue should be fixed

**Comment by jjtpjjj** [comment] 2024-09-13 12:48
> Yes i know, can you test the new testflight build that is out? (i've just pushed it, you may need to remove the item from the continue watching and then the issue is fixed if you are on the new build)

Where can I get a new build that fixes this issue?

**Comment by cranci1** [comment] 2024-09-13 12:49
the iPa or the the Testflight build?

**Comment by jjtpjjj** [comment] 2024-09-13 13:04
I want an ipa.

I found out I can get it here:

https://nightly. link/cranci1/Ryu/workflows/build/main/Ryu-IPA

Thanks for letting me know!

**Comment by cranci1** [comment] 2024-09-13 13:27
@jjtpjjj was this issue fixed on the latest ipa build? (or testflight but you use the ipa i think)

**Comment by jjtpjjj** [comment] 2024-09-13 13:31
The error has not been resolved.

Sometimes an error occurs and the animation can be played, and sometimes it cannot.

**Comment by cranci1** [comment] 2024-09-13 13:39
yeah sometimes it does still show up

**Comment by cranci1** [comment] 2024-09-15 15:44
@jjtpjjj This should be fully fixed on the new commit and so on the new nightly iPA.

**Closed** 2024-09-15 18:45 UTC
Labels: bug
